branches:
  only:
    - develop
    - master

language: go
sudo: false
go: 1.7
cache:
  directories:
  - /node_modules

before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install v6.9.0
  - nvm use v6.9.0

install:
  - npm install -g "gulpjs/gulp#4.0"
  - curl -sSL https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1_Linux-64bit.tar.gz | tar -zxf - -C /tmp/
  - mv /tmp/hugo_0.18.1_linux_amd64/hugo_0.18.1_linux_amd64 /tmp/hugo
  - rm -rf /tmp/hugo_0.18.1_linux_amd64
  - export PATH="/tmp:$PATH"
  - npm install

script:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then gulp build:staging; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then gulp build:prod; fi

# Set correct robots.txt and CNAME files

before_deploy: |
  if [ $TRAVIS_BRANCH == "master" ]; then
    cp ./CNAME ./public/CNAME && cp ./robots.prod.txt ./public/robots.txt
  else
    cp ./robots.dev.txt ./public/robots.txt
  fi

# Deploy master to Github

deploy:
  - provider: script
    script: scripts/deploy_github.sh
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: staging.vamp.io
    region: eu-central-1
    local_dir: public
    skip_cleanup: true
    on:
      branch: develop
